# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

i = 1
fib_num1 = 1
fib_num2 = 0
sum = 0

until fib_num1 + fib_num2 > 4000000
    puts "#{i}. #{result = fib_num1 + fib_num2}"
    if result % 2 == 0
        sum += result
    end
    if i % 2 == 0
        fib_num1 = fib_num1 + fib_num2
    else
        fib_num2 = fib_num1 + fib_num2
    end
    i += 1
end
puts sum